### ISSUE TITLE
As a back-end developer, I want to operate my project with an administrative account so that I can manipulate aspects of my project directly

### ISSUE THREAD

**Issue by PierceCasey** [EvanDyson/AttackOnCollege#16]
Instead of having to open an IDE every time I think of a new achievement to add to the database and be forced to edit the contents in SQL, it would be much easier to edit achievements earned by all users with a master administrative account. This way, when new ideas are thought of later down the line, it will be much easier to add content to our project.

**Comment by EvanDyson** [comment]
admin page is currently available. New issue is getting all new pages correctly working together.
