### ISSUE TITLE
Create a function for extracting just the date of birth from user input

### ISSUE THREAD

**Issue by SaraOsmanovic** [EvanDyson/AttackOnCollege#23]
Currently, the entire string including the time of the day, time zone, day of the week, etc. is added into the database as the date of birth. A new function needs to be made to extract just the day, month, and year from the passed string.

**Comment by PierceCasey** [comment]
Said function has been created, but now needs to be called in a fashion where the user model accepts the changed string.

**Comment by SaraOsmanovic** [comment]
Fully implemented and used to calculate user age, too
