### ISSUE TITLE
Make modifications for the admin account privileges in the code

### ISSUE THREAD

**Issue by SaraOsmanovic** [EvanDyson/AttackOnCollege#27]
Administrator account will have certain features and privileges that regular accounts won't, such as the ability to add achievements straight from the website. To reflect this, along with all the security measures necessary to make this work as intended (i.e. only the administrator can have these specific privileges), we need to make new functions and modify the existing ones to reflect this.

**Comment by PierceCasey** [comment]
Functions that have anything to do with achievements, other than receiving them, have been modified to reflect this change. In addition, certain function privileges have been granted to the administrative account, such as deleting and editing users. This is done through a simple boolean grant and check in functions with desired security.
